title: gbic-peer-instruction-1
hero_image: images/banner.png
description: gbic-peer-instruction-1 description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction to the course
  - title: The Gender Balance in Computing (GBIC) programme
  - title: The Teaching Approach trial
  - title: Research in Peer Instruction
  - title: What is Peer Instruction?
  - title: Data collection using the online survey
  - title: Additional information and guidance
  - title: Summary of Session 1
